version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "[Dependabot] [PIP]"
      include: "scope"
    labels:
      - maintenance
      - bump-pip
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 00:00
      timezone: Asia/Calcutta
    commit-message:
      prefix: "[Dependabot] [GHA]"
      include: "scope"
    labels:
      - maintenance
      - bump-gha
