repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: no-commit-to-branch
      - id: pretty-format-json
        args:
          - --autofix
          - --indent
          - "4"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/pycqa/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --severity-level
          - high
          - --confidence-level
          - high
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --extend-ignore
          - E203
          - --per-file-ignores
          - __init__.py:F401
          - --max-line-length
          - "99"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        pass_filenames: false
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.1
    hooks:
      - id: pylint
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.293
    hooks:
      - id: pyright
        pass_filenames: false
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0.rc1
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries
          - "99"
          - --wrap-descriptions
          - "99"
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.8.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
fail_fast: false
