repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: no-commit-to-branch
      - id: pretty-format-json
        args:
          - --autofix
          - --indent
          - "4"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/pycqa/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args:
          - --overwrite-in-place
          - --profile
          - black
          - --atomic
          - --float-to-top
          - --line-length
          - "99"
          - --remove-redundant-aliases
          - --src-path
          - src
          - --py
          - "310"
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --line-length
          - "99"
          - --target-version
          - py310
          - --safe
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --severity-level
          - high
          - --confidence-level
          - high
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --extend-ignore
          - E203
          - --per-file-ignores
          - __init__.py:F401
          - --max-line-length
          - "99"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --strict
        exclude: conftest|test_
        files: src
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.9
    hooks:
      - id: pylint
        args:
          - --errors-only
          - --enable-all-extensions
          - --persistent
          - "no"
          - --suggestion-mode
          - "yes"
          - --recursive
          - "yes"
          - --output-format
          - colorized
          - --reports
          - "no"
          - --score
          - "yes"
          - --enable
          - all
          - --logging-format-style
          - new
          - --init-import
          - "no"
          - --allow-global-unused-variables
          - "yes"
          - --max-line-length
          - "99"
          - --ignore-comments
          - "yes"
          - --ignore-docstrings
          - "yes"
          - --ignore-imports
          - "yes"
          - --ignore-signatures
          - "yes"
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.6
    hooks:
      - id: vulture
        args:
          - --min-confidence
          - "100"
        pass_filenames: true
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries
          - "99"
          - --wrap-descriptions
          - "99"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.2
    hooks:
      - id: pydocstyle
        args:
          - --convention
          - numpy
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.4.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.10.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
fail_fast: false
