version: 2
formats:
  - epub
  - pdf
python:
  install:
    - path: .
      method: pip
      extra_requirements:
        - doc
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  builder: html
  configuration: docs/source/conf.py
