from .inverses_module import get_negative, get_reciprocal
from .operations_module import add_numbers, multiply_numbers

def subtract_numbers(first_number: float, second_number: float) -> float: ...
def divide_numbers(first_number: float, second_number: float) -> float: ...
