__all__ = ["add_numbers", "multiply_numbers"]

def add_numbers(left_addend: float, right_addend: float) -> float: ...
def multiply_numbers(left_multiplicand: float, right_multiplicand: float) -> float: ...
