name: autoflake-workflow-name
on:
  pull_request:
    branches:
      - main
jobs:
  autoflake-job-identifier:
    name: autoflake job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: install nox
        run: python3 -m pip install nox
      - name: autoflake step name
        run: nox --session autoflake
