name: bump-workflow-name
run-name: bump workflow run name
on:
  workflow_dispatch:
    inputs:
      semantic-version-identifier:
        description: name of protected semantic version
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
defaults:
  run:
    shell: bash
jobs:
  bump-job-identifier:
    name: bump job name
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment-identifier }}
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          check-latest: true
          architecture: x64
          cache: pip
      - id: install-step-identifier
        name: install bump-my-version
        run: python3 -m pip install bump-my-version
        shell: bash
      - id: branch-step-identifier
        name: create new branch
        run: git branch bump-branch-name
        shell: bash
      - id: bump-step-identifier
        name: bump package version
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: git switch bump-branch-name && bump-my-version bump -vvv ${{ inputs.semantic-version-identifier }}
        shell: bash
      - id: pull-request-step-identifier
        name: create new pull-request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base main --fill --head bump-branch-name --label maintenance --label bump-package
        shell: bash
