name: code-quality-workflow-name
run-name: code quality workflow run name
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  pre-commit-job-identifier:
    name: pre-commit job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          check-latest: true
          architecture: x64
          cache: pip
      - name: run all pre-commit hooks
        env:
          SKIP: no-commit-to-branch
        uses: ./.github/actions/nox-sessions-action-identifier
        with:
          session-name-input-identifier: pre_commit
  unit-test-job-identifier:
    needs: pre-commit-job-identifier
    name: unit test job name
    uses: ./.github/workflows/test.yml
