name: format-workflow-name
run-name: format workflow run name
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  format-job-identifier:
    name: format job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          check-latest: true
          architecture: x64
          cache: pip
      - name: run formatters
        uses: ./.github/actions/nox-tags-action-identifier
        with:
          tag-name-input-identifier: format
