name: format-workflow-name
run-name: format workflow run name
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
defaults:
  run:
    shell: bash
jobs:
  format-job-identifier:
    name: format job name
    strategy:
      fail-fast: false
      matrix:
        runner-platform:
          - ubuntu-latest
        python-version:
          - "3.10"
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          architecture: x64
          cache: pip
      - name: run formatters on python ${{ matrix.python-version }}
        uses: ./.github/actions/nox-tags-action-identifier
        with:
          tag-name-input-identifier: format
