name: format-workflow-name
run-name: format workflow run name
on:
  workflow_call:
  workflow_dispatch:
jobs:
  autoflake-job-identifier:
    name: autoflake job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: run autoflake
        uses: .github/actions/autoflake-action-identifier
  black-job-identifier:
    name: black job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: run black
        uses: .github/actions/black-action-identifier
