name: lint-workflow-name
run-name: lint workflow run name
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  lint-job-identifier:
    name: lint job name
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          architecture: x64
          cache: pip
      - name: run linters on python ${{ matrix.python-version }}
        uses: ./.github/actions/nox-tags-action-identifier
        with:
          tag-name-input-identifier: lint
          python-version-input-identifier: ${{ matrix.python-version }}
