name: lint-workflow-name
run-name: lint workflow run name
on:
  workflow_call:
  workflow_dispatch:
jobs:
  bandit-job-identifier:
    name: bandit job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: run bandit
        uses: .github/actions/bandit-action-identifier
  flake8-job-identifier:
    name: flake8 job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: run flake8
        uses: .github/actions/flake8-action-identifier
