name: format-workflow-name
run-name: format workflow run name
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  format-job-identifier:
    name: format job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: run formatters
        uses: ./.github/actions/nox-tags-action-identifier/action.yml
        with:
          tag-name-input-identifier: format
  lint-3-10-job-identifier:
    name: lint 3.10 job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: run linters
        uses: ./.github/actions/nox-tags-action-identifier/action.yml
        with:
          tag-name-input-identifier: lint
          python-version-input-identifier: 3.10
  lint-3-11-job-identifier:
    name: lint 3.11 job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: run linters
        uses: ./.github/actions/nox-tags-action-identifier/action.yml
        with:
          tag-name-input-identifier: lint
          python-version-input-identifier: 3.11
  test-coverage-3-10-job-identifier:
    name: test coverage 3.10 job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: run unit test coverage
        uses: ./.github/actions/nox-sessions-action-identifier/action.yml
        with:
          session-name-input-identifier: pytest
          python-version-input-identifier: 3.10
  test-coverage-3-11-job-identifier:
    name: test coverage 3.11 job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: run unit test coverage
        uses: ./.github/actions/nox-sessions-action-identifier/action.yml
        with:
          session-name-input-identifier: pytest
          python-version-input-identifier: 3.11
