name: format-workflow-name
run-name: format workflow run name
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  format-job-identifier:
    name: format job name
    uses: ./.github/workflows/format.yml
  lint-job-identifier:
    name: lint job name
    uses: ./.github/workflows/lint.yml
  test-coverage-job-identifier:
    name: test coverage job name
    uses: ./.github/workflows/test-coverage.yml
