name: pre-commit-workflow-name
run-name: pre-commit workflow run name
on: push
defaults:
  run:
    shell: bash
jobs:
  pre-commit-job-identifier:
    name: pre-commit job name
    strategy:
      fail-fast: false
      matrix:
        runner-platform:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          architecture: x64
      - name: run all pre-commit hooks on python ${{ matrix.python-version }}
        uses: ./.github/actions/nox-sessions-action-identifier
        with:
          session-name-input-identifier: pre_commit
          python-version-input-identifier: ${{ matrix.python-version }}
