name: test-workflow-name
run-name: test workflow run name
on:
  workflow_call:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test-job-identifier:
    name: test job name
    strategy:
      fail-fast: false
      matrix:
        runner-platform:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
      max-parallel: 5
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: |
            ${{ matrix.python-version }}
            3.10
          check-latest: true
          architecture: x64
          cache: pip
      - name: run unit tests on python ${{ matrix.python-version }} in runner ${{ matrix.runner-platform }}
        uses: ./.github/actions/nox-sessions-action-identifier
        with:
          session-name-input-identifier: pytest
          python-version-input-identifier: ${{ matrix.python-version }}
      - name: upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage_xml_report.xml
          flags: ${{ matrix.python-version }},${{ matrix.runner-platform }}
