name: test-workflow-name
run-name: test workflow run name
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test-coverage-job-identifier:
    name: test coverage job name
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest
    steps:
      - name: run test coverage
        uses: .github/actions/test-coverage-action-identifier
